import test from 'node:test';import assert from 'node:assert/strict';
import {FrameClock,interpolate} from '../src/timing.js';
import {Director,controlRival,DecisionClient} from '../src/rivals.js';
import {sanitizeState,createDecisionService} from '../server/decision-service.mjs';
test('catch-up is bounded after a long stall, interpolation remains in range',()=>{const c=new FrameClock();let n=0;const alpha=c.advance(4,()=>n++);assert.equal(n,8);assert.ok(alpha>=0&&alpha<1);assert.ok(c.dropped>.1);assert.equal(interpolate({s:1},{s:3},.5,{}).s,2)});
test('120Hz simulation advances equally at 30 and 144 render FPS',()=>{const run=fps=>{const c=new FrameClock();let t=0;for(let i=0;i<fps*10;i++)c.advance(1/fps,dt=>t+=dt);return t};assert.ok(Math.abs(run(30)-run(144))<1/120+.00001)});
test('damage overrides model pressure and recovery has dwell time',()=>{const d=new Director(),p={health:100,time:25,v:40};d.update(p,25);p.health=50;p.time=28;d.update(p,.1,{tactic:'defend',encounter:'pressure'});assert.equal(d.encounter,'recover');p.time=35;d.update(p,7,{tactic:'defend',encounter:'pressure'});// Model request is honoured once the 5 s recover window closes — intended behaviour, not a regression.
assert.equal(d.encounter,'pressure');p.v=20;p.time=42;d.update(p,7);assert.equal(d.encounter,'balanced')});
test('rivals have bounded acceleration, avoid traffic and preserve speed cap',()=>{const p={s:100,x:0,time:30,health:100},d=new Director(),a={s:90,x:0,y:0,v:25,target:40,stun:0,attack:0};controlRival(a,0,p,[{s:96,x:0,y:0,v:15}],d,.01);assert.ok(a.lane>0);assert.ok(a.v<=25);for(let i=0;i<1000;i++){p.time+=.01;controlRival(a,0,p,[],d,.01)}assert.ok(Math.abs(a.x)<=7.5);assert.ok(a.v<=42.8+.001)});
test('stale remote result cannot cross a race reset',async()=>{let finish;const c=new DecisionClient(()=>new Promise(r=>finish=r));const p={time:4,v:30,health:100,y:0},setup={brain:'laya'};c.tick(p,[],setup);c.reset();finish({ok:true,json:async()=>({tactic:'defend',encounter:'pressure'})});await new Promise(r=>setTimeout(r,0));assert.equal(c.consume(),null)});
test('offline model is nonblocking and invalid data never reaches controller',async()=>{const c=new DecisionClient(async()=>({ok:true,json:async()=>({tactic:'teleport',encounter:'pressure'})}));c.tick({time:4,v:30,health:100,y:0},[],{brain:'laya'});await new Promise(r=>setTimeout(r,0));assert.equal(c.consume(),null);assert.match(c.status,/LOCAL AI/);const service=createDecisionService(false);assert.equal(service.status,'disabled');await assert.rejects(service.decide({}));assert.throws(()=>sanitizeState({speed:'fast'}));});

test('pressure makes rivals attempt a pass earlier without increasing speed limits',()=>{const p={s:100,x:0,time:30,health:100},normal=new Director(),hard=new Director();hard.encounter='pressure';const create=()=>({s:60,x:0,y:0,v:30,target:40,stun:0,attack:0});const a=create(),b=create();controlRival(a,0,p,[],normal,.01);controlRival(b,0,p,[],hard,.01);assert.equal(a.tactic,'race');assert.equal(b.tactic,'overtake');assert.equal(a.speedLimit,b.speedLimit)});
