export class AudioEngine{
constructor(){this.enabled=false;this.musicVolume=.5;this.fxVolume=.7;this.tick=0;this.next=0;this.sfxVoices=0;this.maxSfxVoices=6;this.encounter='balanced';this.worldKind='city';this.lastHz=0}
async start(){if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();const c=this.ctx;this.master=c.createGain();this.master.gain.value=.45;const limiter=c.createDynamicsCompressor();this.master.connect(limiter);limiter.connect(c.destination);this.fx=c.createGain();this.fx.connect(this.master);this.music=c.createGain();this.musicFade=c.createGain();this.music.connect(this.musicFade);this.musicFade.connect(this.master);this.sfx=c.createGain();this.sfx.connect(this.fx);this.motor=c.createOscillator();this.motor.type='sawtooth';this.motor2=c.createOscillator();this.motor2.type='triangle';this.filter=c.createBiquadFilter();this.filter.type='lowpass';this.engineGain=c.createGain();this.engineGain.gain.value=.03;this.motor.connect(this.filter);this.motor2.connect(this.filter);this.filter.connect(this.engineGain);this.engineGain.connect(this.fx);this.motor.start();this.motor2.start();const buffer=c.createBuffer(1,c.sampleRate*2,c.sampleRate);const d=buffer.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;this.noiseBuffer=buffer;this.wind=c.createBufferSource();this.wind.buffer=buffer;this.wind.loop=true;this.windFilter=c.createBiquadFilter();this.windFilter.type='lowpass';this.windFilter.frequency.value=700;this.windGain=c.createGain();this.windGain.gain.value=0;this.wind.connect(this.windFilter);this.windFilter.connect(this.windGain);this.windGain.connect(this.fx);this.wind.start();this.rain=c.createBufferSource();this.rain.buffer=buffer;this.rain.loop=true;const rf=c.createBiquadFilter();rf.type='bandpass';rf.frequency.value=4200;rf.Q.value=.7;this.rainGain=c.createGain();this.rainGain.gain.value=0;this.rain.connect(rf);rf.connect(this.rainGain);this.rainGain.connect(this.fx);this.rain.start();this.tire=c.createBufferSource();this.tire.buffer=buffer;this.tire.loop=true;const tf=c.createBiquadFilter();tf.type='bandpass';tf.frequency.value=2200;tf.Q.value=2;this.tireGain=c.createGain();this.tireGain.gain.value=0;this.tire.connect(tf);tf.connect(this.tireGain);this.tireGain.connect(this.fx);this.tire.start();if(c.createStereoPanner){this.pan=c.createStereoPanner();this.hum=c.createBufferSource();this.hum.buffer=buffer;this.hum.loop=true;const hf=c.createBiquadFilter();hf.type='bandpass';hf.frequency.value=300;hf.Q.value=1.2;this.humGain=c.createGain();this.humGain.gain.value=0;this.hum.connect(hf);hf.connect(this.pan);this.pan.connect(this.humGain);this.humGain.connect(this.fx);this.hum.start()}this.next=c.currentTime+.1}await this.ctx.resume();this.enabled=true}
setEnabled(v){this.enabled=v;if(this.ctx){if(v){this.ctx.resume();this.next=this.ctx.currentTime+.1}else this.ctx.suspend()}}
note(freq,time,duration,volume,type='triangle',destination=this.music){const c=this.ctx,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(freq,time);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(volume,time+.012);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(destination);o.start(time);o.stop(time+duration+.03)}
noise(time,duration,volume,frequency=3000,destination=this.sfx){const sfx=destination===this.sfx;if(sfx&&this.sfxVoices>=this.maxSfxVoices)return;const c=this.ctx,s=c.createBufferSource(),g=c.createGain(),f=c.createBiquadFilter();s.buffer=this.noiseBuffer;f.type='highpass';f.frequency.value=frequency;s.connect(f);f.connect(g);g.connect(destination);g.gain.setValueAtTime(volume,time);g.gain.exponentialRampToValueAtTime(.0001,time+duration);if(sfx){this.sfxVoices++;s.onended=()=>this.sfxVoices--}s.start(time);s.stop(time+duration)}
update(p,bike,riding,throttle,weather,grip,rivals,traffic,tScale=1){if(!this.ctx||!this.enabled)return;const c=this.ctx,t=c.currentTime;this.fx.gain.setTargetAtTime(this.fxVolume,t,.05);this.music.gain.setTargetAtTime(this.musicVolume,t,.05);const flying=riding&&(p.flight||p.landing);const gearRatio=(bike.ratios||[2.8,1.9,1.4,1.05,.85])[(p.gear||1)-1]||1;const hz=Math.min(340,Math.max(22,flying?90+p.v*.8+(p.boosting?40:0):(riding?p.rpm*gearRatio:1300)/60*bike.cylinders/2));const dip=tScale<1?.55+.45*tScale:1;const tc=hz>this.lastHz?.03:.12;this.motor.frequency.setTargetAtTime(hz*dip,t,tc);this.motor2.frequency.setTargetAtTime(hz*(flying?1.006:.502)*dip,t,tc);this.lastHz=hz;this.filter.frequency.setTargetAtTime(200+(riding?p.rpm:1300)*.2,t,.08);this.engineGain.gain.setTargetAtTime(riding?(throttle?.085:.04):.012,t,.1);this.windGain.gain.setTargetAtTime(riding?.08*Math.min(1,p.v/80):.004,t,.2);this.windFilter.frequency.setTargetAtTime(500+Math.min(1,p.v/90)*2600,t,.3);if(riding&&p.v>70)this.windGain.gain.value+=Math.sin(t*23)*.006;this.rainGain.gain.setTargetAtTime(weather==='rain'?.05+Math.min(.03,p.v*.0003):0,t,.4);const tireSlip=riding?Math.max(0,1-(grip??1))*Math.min(1,Math.abs(p.vx||0)/3):0;this.tireGain.gain.setTargetAtTime(tireSlip*.09,t,.1);if(this.pan){let near=null,nd=15;for(const a of[...(rivals||[]),...(traffic||[])]){const d=Math.abs(a.s-p.s);if(d<nd){nd=d;near=a}}if(near&&riding){this.pan.pan.setTargetAtTime(Math.max(-1,Math.min(1,(near.x-p.x)/6)),t,.1);this.humGain.gain.setTargetAtTime(.015,t,.1)}else this.humGain.gain.setTargetAtTime(0,t,.15)}
// Original 112 BPM minor-key bass, arpeggio, kick, and hats. Schedule ahead in audio time. Layers react to the director encounter and per-world mood.
if(this.next<t-.3)this.next=t+.03;while(this.next<t+.15){const n=this.tick++,s=n%16,bar=Math.floor(n/16)%4,root=[1,.7937,1.1892,.8909][bar]*(this.worldRoot||55),at=this.next;if(s%4===0){const o=c.createOscillator(),g=c.createGain();o.frequency.setValueAtTime(135,at);o.frequency.exponentialRampToValueAtTime(this.worldKind==='alpine'?52:38,at+.15);g.gain.setValueAtTime(.22,at);g.gain.exponentialRampToValueAtTime(.0001,at+.23);o.connect(g);g.connect(this.music);o.start(at);o.stop(at+.24)}if(s%2===0)this.note(root*(s===6?2:1),at,.2,this.encounter==='pressure'?.13:.09,'sawtooth');if(s%2===1&&this.encounter!=='recover'&&(this.worldKind!=='ocean'||s%4===1))this.noise(at,.045,.026,6500,this.music);if(s===4||s===12)this.noise(at,.12,.07,1500,this.music);const semitones=this.worldKind==='desert'?[0,7,11,15,7,11,19,15]:[0,7,12,15,7,12,19,15];this.note(root*4*2**(semitones[s%8]/12),at,.21,{pressure:.04,recover:.012}[this.encounter]||.023,'triangle');this.next+=60/112/4}}
crash(kind='traffic'){if(!this.ctx||!this.enabled||this.sfxVoices>=this.maxSfxVoices)return;const t=this.ctx.currentTime;if(kind==='rival'){this.note(120,t,.18,.22,'square',this.sfx);this.noise(t,.22,.16,2200)}else if(kind==='structure'){this.note(48,t,.4,.28,'sawtooth',this.sfx);this.noise(t,.5,.3,900)}else if(kind==='debris')this.noise(t,.15,.18,4500);else{this.note(65,t,.3,.2,'sawtooth',this.fx);const s=this.ctx.createBufferSource(),g=this.ctx.createGain();s.buffer=this.noiseBuffer;s.connect(g);g.connect(this.fx);g.gain.setValueAtTime(.22,t);g.gain.exponentialRampToValueAtTime(.0001,t+.35);this.sfxVoices++;s.onended=()=>this.sfxVoices--;s.start();s.stop(t+.36)}}
uiClick(){if(!this.ctx||!this.enabled)return;this.note(880,this.ctx.currentTime,.08,.12,'square',this.sfx)}
uiHover(){if(!this.ctx||!this.enabled)return;this.note(660,this.ctx.currentTime,.04,.05,'sine',this.sfx)}
countdownBeep(n){if(!this.ctx||!this.enabled)return;this.note(n>0?520:1040,this.ctx.currentTime,.15,.18,'square',this.sfx)}
fadeMusic(target,duration=.6){if(!this.ctx)return;const t=this.ctx.currentTime;this.musicFade.gain.cancelScheduledValues(t);this.musicFade.gain.setTargetAtTime(target,t,duration/3)}
}
